package presentationLayer;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.SpringLayout;

public class ConnectionWindow {

	private final String DEFAULT_LOGIN = "user";
	private final String DEFAULT_PASSWORD = "logitech1";
	
	private final Dimension FRAME_SIZE = new Dimension(360, 220);
	private final int TEXT_FIELD_NUMBER_OF_COLUMNS = 10;
	
	private JFrame frame;
	private Container frameContentPane;
	private SpringLayout frameSpringLayout;
	private JLabel infoLabel;
	private JLabel loginLabel, passwordLabel;
	private JFormattedTextField loginTextField;
	private JPasswordField passwordField;
	private JButton connectButton;

	public ConnectionWindow() {
		initialize();
	}
	
	public void show() {
		frame.setVisible(true);
	}
	
	public void close() {
		frame.setVisible(false);
	}
	
	public void addConnectButtonListener(ActionListener actionListener) {
		connectButton.addActionListener(actionListener);
	}
	
	public String getLogin() {
		return loginTextField.getText();
	}
	
	public String getPassword() {
		return passwordField.getText(); //FIXME: maybe I will
	}
	
	public void displayMessageDialog(String title, String message) {
		JOptionPane.showMessageDialog(frame, message, title, JOptionPane.PLAIN_MESSAGE);
	}
	
	private void initialize() {
		createFrame();
		createFrameLayout();
		createInfoLabel();
		createInputComponents();		
		createButtons();
		addComponentsToLayout();
	}

	private void createFrame() {
		frame = new JFrame("Bank App - Connect");
		frameContentPane = frame.getContentPane();
		frame.setSize(FRAME_SIZE);
		frame.setResizable(false);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		centerFrame(frame);
	}
	
	private void centerFrame(JFrame frame) {
		frame.setLocationRelativeTo(null);
	}
	
	private void createFrameLayout() {
		frameSpringLayout = new SpringLayout();
		frameContentPane.setLayout(frameSpringLayout);
	}
	
	private void createInfoLabel() {
		infoLabel = new JLabel("Welcome! Log into MySql database.");
	}
	
	private void createInputComponents() {
		createLoginInputComponents();
		createPasswordInputComponents();
	}

	private void createLoginInputComponents() {
		loginLabel = new JLabel("Login: ");
		loginLabel.setFont(new Font("Tahoma", Font.PLAIN, 11));		
		loginTextField = new JFormattedTextField();
		loginTextField.setText(DEFAULT_LOGIN);
		loginTextField.setColumns(TEXT_FIELD_NUMBER_OF_COLUMNS);
	}
	
	private void createPasswordInputComponents() {
		passwordLabel = new JLabel("Password: ");		
		passwordLabel.setFont(new Font("Tahoma", Font.PLAIN, 11));
		passwordField = new JPasswordField();
		passwordField.setText(DEFAULT_PASSWORD);
		passwordField.setColumns(TEXT_FIELD_NUMBER_OF_COLUMNS);
	}

	private void createButtons() {
		Dimension buttonSize = new Dimension(150, 30);
		connectButton = new JButton("Connect");
		connectButton.setSize(buttonSize);
	}
	
	private void addComponentsToLayout() {
		putLayoutConstraints();
		frameContentPane.add(infoLabel);
		frameContentPane.add(loginLabel);
		frameContentPane.add(loginTextField);
		frameContentPane.add(passwordLabel);
		frameContentPane.add(passwordField);
		frameContentPane.add(connectButton);
	}
	
	private void putLayoutConstraints() {
		//code auto-generated by Window Builder
		frameSpringLayout.putConstraint(SpringLayout.NORTH, connectButton, 25, SpringLayout.SOUTH, passwordField);
		frameSpringLayout.putConstraint(SpringLayout.WEST, connectButton, 0, SpringLayout.WEST, loginTextField);
		frameSpringLayout.putConstraint(SpringLayout.EAST, connectButton, 0, SpringLayout.EAST, loginTextField);
		frameSpringLayout.putConstraint(SpringLayout.NORTH, loginLabel, 67, SpringLayout.NORTH, frame.getContentPane());
		frameSpringLayout.putConstraint(SpringLayout.WEST, loginLabel, 85, SpringLayout.WEST, frame.getContentPane());
		frameSpringLayout.putConstraint(SpringLayout.EAST, loginLabel, -237, SpringLayout.EAST, frame.getContentPane());
		frameSpringLayout.putConstraint(SpringLayout.NORTH, loginTextField, 30, SpringLayout.SOUTH, infoLabel);
		frameSpringLayout.putConstraint(SpringLayout.WEST, loginTextField, 3, SpringLayout.EAST, loginLabel);
		frameSpringLayout.putConstraint(SpringLayout.WEST, passwordLabel, 64, SpringLayout.WEST, frame.getContentPane());
		frameSpringLayout.putConstraint(SpringLayout.EAST, passwordLabel, 0, SpringLayout.EAST, loginLabel);
		frameSpringLayout.putConstraint(SpringLayout.NORTH, passwordField, 6, SpringLayout.SOUTH, loginTextField);
		frameSpringLayout.putConstraint(SpringLayout.NORTH, infoLabel, 20, SpringLayout.NORTH, frame.getContentPane());
		frameSpringLayout.putConstraint(SpringLayout.EAST, infoLabel, -94, SpringLayout.EAST, frame.getContentPane());
		frameSpringLayout.putConstraint(SpringLayout.NORTH, passwordLabel, 12, SpringLayout.SOUTH, loginLabel);
		frameSpringLayout.putConstraint(SpringLayout.WEST, passwordField, 3, SpringLayout.EAST, loginLabel);
	}
	
}
