package presentationLayer;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.JButton;
import java.awt.Font;
import javax.swing.JPasswordField;
import javax.swing.JCheckBox;

public class CustomerInformationWindow {

	private final Dimension frameSize = new Dimension(275, 230);
	
	private JFrame frame;
	private Container frameContentPane;
	
	private JLabel idLabel;
	private JLabel nameLabel;
	private JLabel surnameLabel;
	private JLabel passwordLabel;
	
	private JTextField idTextField;
	private JTextField nameTextField;
	private JTextField surnameTextField;
	private JPasswordField passwordField;
	
	private JButton acceptButton;
	private JButton cancelButton;

	private JCheckBox showPasswordCheckBox;
	
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					CustomerInformationWindow window = new CustomerInformationWindow();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	public CustomerInformationWindow() {
		initialize();
	}

	private void initialize() {
		initializeFrame();
		initializeLabels();
		initializeInputFields();
		initializeButtons();
		initializeCheckBox();
		addComponents();
	}

	private void initializeFrame() {
		frame = new JFrame("Customer");
		frameContentPane = frame.getContentPane();
		frame.setSize(frameSize);
		frame.setLocationRelativeTo(null);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frameContentPane.setLayout(null);
	}
	
	private void initializeLabels() {
		idLabel = new JLabel("ID:");
		formatLabel(idLabel);
		
		nameLabel = new JLabel("Name:");
		formatLabel(nameLabel);
		
		surnameLabel = new JLabel("Surname:");
		formatLabel(surnameLabel);
		
		passwordLabel = new JLabel("Password:");
		formatLabel(passwordLabel);
	}

	private void formatLabel(JLabel label) {
		label.setFont(new Font("Tahoma", Font.PLAIN, 11));
		label.setHorizontalAlignment(SwingConstants.RIGHT);
	}
	
	private void initializeInputFields() {
		idTextField = new JTextField();
		idTextField.setColumns(10);
		
		nameTextField = new JTextField();
		nameTextField.setColumns(10);
		
		surnameTextField = new JTextField();
		surnameTextField.setColumns(10);
		
		passwordField = new JPasswordField();
	}
	
	private void initializeButtons() {
		acceptButton = new JButton("Accept");
		cancelButton = new JButton("Cancel");
	}
	
	private void initializeCheckBox() {
		showPasswordCheckBox = new JCheckBox("Show password");
		showPasswordCheckBox.setFont(new Font("Tahoma", Font.PLAIN, 10));
	}
	
	private void addComponents() {
		setBounds();
		frameContentPane.add(idLabel);
		frameContentPane.add(nameLabel);
		frameContentPane.add(surnameLabel);
		frameContentPane.add(passwordLabel);
		
		frameContentPane.add(idTextField);
		frameContentPane.add(nameTextField);
		frameContentPane.add(surnameTextField);
		frameContentPane.add(passwordField);
		
		frameContentPane.add(acceptButton);
		frameContentPane.add(cancelButton);
		
		frameContentPane.add(showPasswordCheckBox);
	}

	private void setBounds() {
		//auto-generated by Window Designer
		idLabel.setBounds(24, 14, 46, 14);
		nameLabel.setBounds(24, 42, 46, 14);
		surnameLabel.setBounds(10, 70, 60, 14);
		passwordLabel.setBounds(10, 102, 60, 14);
		idTextField.setBounds(80, 11, 110, 20);
		nameTextField.setBounds(80, 39, 110, 20);
		surnameTextField.setBounds(80, 67, 110, 20);
		passwordField.setBounds(80, 98, 110, 20);
		acceptButton.setBounds(35, 157, 89, 23);
		cancelButton.setBounds(131, 157, 89, 23);
		showPasswordCheckBox.setBounds(80, 125, 129, 23);
	}
}
