package presentationLayer;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.SpringLayout;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JTable;

public class ManageWindow {

	private final Dimension frameSize = new Dimension(800, 600);
	
	private JFrame frame;
	private Container frameContentPane;
	private JLabel cutomersLabel;
	private JLabel bankAccountsLabel;
	private JButton addButton;
	private JButton changeButton;
	private JButton deleteButton;
	private JTable customersTable;
	private JTable bankAccountsTable;
	
	private SpringLayout springLayout;

	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					ManageWindow window = new ManageWindow();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	public ManageWindow() {
		initialize();
	}

	private void initialize() {
		initializeFrame();
		setupFrameLayout();
		initializeLabels();
		initializeButtons();
		initializeTables();
		addComponentsToFrame();
	}
	
	private void initializeFrame() {
		frame = new JFrame("Bank App - Manage");
		frameContentPane = frame.getContentPane();
		frame.setSize(frameSize);
		centerFrame(frame);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}

	private void centerFrame(JFrame frame) {
		frame.setLocationRelativeTo(null);
	}
	
	private void setupFrameLayout() {
		springLayout = new SpringLayout();
		frameContentPane.setLayout(springLayout);
	}
	
	private void initializeLabels() {
		cutomersLabel = new JLabel("Customers");
		bankAccountsLabel = new JLabel("Bank accounts");
	}
	
	private void initializeButtons() {
		addButton = new JButton("Add");
		changeButton = new JButton("Change");
		deleteButton = new JButton("Delete");
	}
	
	private void initializeTables() {
		customersTable = new JTable();
		bankAccountsTable = new JTable();
	}
	
	private void addComponentsToFrame() {
		putConstraints();
		frameContentPane.add(cutomersLabel);
		frameContentPane.add(bankAccountsLabel);
		frameContentPane.add(addButton);
		frameContentPane.add(changeButton);
		frameContentPane.add(deleteButton);
		frameContentPane.add(customersTable);
		frameContentPane.add(bankAccountsTable);
	}

	private void putConstraints() {
		//code auto-generated by Window Designer
		springLayout.putConstraint(SpringLayout.NORTH, cutomersLabel, 10, SpringLayout.NORTH, frameContentPane);
		springLayout.putConstraint(SpringLayout.WEST, cutomersLabel, 70, SpringLayout.WEST, frameContentPane);
		springLayout.putConstraint(SpringLayout.NORTH, bankAccountsLabel, 0, SpringLayout.NORTH, cutomersLabel);
		springLayout.putConstraint(SpringLayout.EAST, bankAccountsLabel, -294, SpringLayout.EAST, frameContentPane);
		springLayout.putConstraint(SpringLayout.NORTH, addButton, 190, SpringLayout.NORTH, frameContentPane);
		springLayout.putConstraint(SpringLayout.EAST, addButton, -10, SpringLayout.EAST, frameContentPane);
		springLayout.putConstraint(SpringLayout.NORTH, deleteButton, 12, SpringLayout.SOUTH, addButton);
		springLayout.putConstraint(SpringLayout.WEST, deleteButton, 0, SpringLayout.WEST, addButton);
		springLayout.putConstraint(SpringLayout.EAST, deleteButton, -10, SpringLayout.EAST, frameContentPane);
		springLayout.putConstraint(SpringLayout.NORTH, changeButton, 18, SpringLayout.SOUTH, deleteButton);
		springLayout.putConstraint(SpringLayout.WEST, changeButton, 669, SpringLayout.WEST, frameContentPane);
		springLayout.putConstraint(SpringLayout.EAST, changeButton, 0, SpringLayout.EAST, addButton);
		springLayout.putConstraint(SpringLayout.NORTH, customersTable, 6, SpringLayout.SOUTH, cutomersLabel);
		springLayout.putConstraint(SpringLayout.WEST, customersTable, 10, SpringLayout.WEST, frameContentPane);
		springLayout.putConstraint(SpringLayout.SOUTH, customersTable, 527, SpringLayout.SOUTH, cutomersLabel);
		springLayout.putConstraint(SpringLayout.EAST, customersTable, 319, SpringLayout.WEST, frameContentPane);
		springLayout.putConstraint(SpringLayout.WEST, addButton, 16, SpringLayout.EAST, bankAccountsTable);
		springLayout.putConstraint(SpringLayout.NORTH, bankAccountsTable, 6, SpringLayout.SOUTH, bankAccountsLabel);
		springLayout.putConstraint(SpringLayout.WEST, bankAccountsTable, 6, SpringLayout.EAST, customersTable);
		springLayout.putConstraint(SpringLayout.SOUTH, bankAccountsTable, 527, SpringLayout.SOUTH, bankAccountsLabel);
		springLayout.putConstraint(SpringLayout.EAST, bankAccountsTable, 334, SpringLayout.EAST, customersTable);
	}
}
