package presentationLayer;

import java.awt.Container;
import java.awt.Dimension;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import java.awt.Font;
import javax.swing.JScrollPane;

public class ManageWindow {

	private final Dimension frameSize = new Dimension(800, 400);
	
	private JFrame frame;
	private Container frameContentPane;
	private JLabel cutomersLabel;
	private JLabel bankAccountsLabel;
	
	private JButton addCustomerButton;
	private JButton changeCustomerButton;
	private JButton deleteCustomerButton;
	
	private JButton addBankAccountButton;
	private JButton deleteBankAccountButton;
	private JButton changeBankAccountButton;
	
	private JScrollPane customersTableScrollPane;
	private DefaultTableModel customersTableModel;
	private JTable customersTable;
	private JTable bankAccountsTable;
	
	public ManageWindow() {
		initialize();
	}
	
	public void show() {
		frame.setVisible(true);
	}
	
	public void putCustomersInfoIntoTable(String[][] allCustomersInfoForTable) {
		for(int rowIndex = 0; rowIndex < allCustomersInfoForTable.length; rowIndex++) {
			customersTableModel.addRow(allCustomersInfoForTable[rowIndex]);
		}
	}

	private void initialize() {
		initializeFrame();
		initializeLabels();
		initializeButtons();
		initializeTables();
		addComponentsToFrame();
	}
	
	private void initializeFrame() {
		frame = new JFrame("Bank App - Manage");
		frameContentPane = frame.getContentPane();
		frameContentPane.setLayout(null);
		frame.setSize(frameSize);
		centerFrame(frame);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}

	private void centerFrame(JFrame frame) {
		frame.setLocationRelativeTo(null);
	}
	
	private void initializeLabels() {
		cutomersLabel = new JLabel("Customers");
		cutomersLabel.setFont(new Font("Tahoma", Font.BOLD, 14));
		
		bankAccountsLabel = new JLabel("Bank accounts");
		bankAccountsLabel.setFont(new Font("Tahoma", Font.BOLD, 14));
	}
	
	private void initializeButtons() {
		addCustomerButton = new JButton("Add");
		changeCustomerButton = new JButton("Change");
		deleteCustomerButton = new JButton("Delete");
		addBankAccountButton = new JButton("Add");
		deleteBankAccountButton = new JButton("Delete");
		changeBankAccountButton = new JButton("Change");
	}
	
	private void initializeTables() {
		initializeCustomersTable();
		bankAccountsTable = new JTable();
	}
	
	private void initializeCustomersTable() {
		String[] customersTableColumnNames = {"ID", "NAME", "SURNAME", "PASSWORD"};
		int initialNumberOfRows = 0;
		customersTableModel = new DefaultTableModel(initialNumberOfRows, customersTableColumnNames.length);
		customersTableModel.setColumnIdentifiers(customersTableColumnNames);
		customersTable = new JTable(customersTableModel);
		customersTableScrollPane = new JScrollPane();
		customersTableScrollPane.add(customersTable);
		customersTableScrollPane.setViewportView(customersTable);
	}
	
	private void addComponentsToFrame() {
		setBounds();
		frameContentPane.add(cutomersLabel);
		frameContentPane.add(bankAccountsLabel);
		frameContentPane.add(addCustomerButton);
		frameContentPane.add(changeCustomerButton);
		frameContentPane.add(deleteCustomerButton);
		frameContentPane.add(addBankAccountButton);
		frameContentPane.add(deleteBankAccountButton);
		frameContentPane.add(changeBankAccountButton);
		frameContentPane.add(customersTableScrollPane);
		frameContentPane.add(bankAccountsTable);
	}

	private void setBounds() {
		//code auto-generated by Window Designer
		cutomersLabel.setBounds(168, 30, 75, 17);
		bankAccountsLabel.setBounds(553, 118, 101, 17);
		addCustomerButton.setBounds(47, 313, 105, 23);
		changeCustomerButton.setBounds(198, 313, 105, 23);
		deleteCustomerButton.setBounds(347, 313, 105, 23);
		addBankAccountButton.setBounds(478, 313, 80, 23);
		deleteBankAccountButton.setBounds(664, 313, 80, 23);
		changeBankAccountButton.setBounds(568, 313, 80, 23);
		customersTableScrollPane.setBounds(47, 58, 405, 244);
		bankAccountsTable.setBounds(478, 146, 268, 156);
	}

}
